name: cd_docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> "$GITHUB_ENV"
    - uses: tradeshift/actions-docker@v1
      with:
        repository: 063399264027.dkr.ecr.eu-west-1.amazonaws.com/tradeshift-base/openflagr
        platform: linux/amd64,linux/arm64
        aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
